########## Horizon Config ##########
# Welcome to Horizon's configuration file.
# Before changing anything, please note that all settings has been tested.
# It is recommended not to change any settings if it is not necessary.
#
# Issue-Tracker: https://github.com/CraftG/Horizon/issues
# Discord: https://discord.gg/s8RyWzJ
# I hope you have a good time here.
####################################

settings:
  # Disable drag down feature?
  enable_drag_down: true
  # If drag down feature is disabled, should Horizon use drag back instead?
  drag_back_instead: true

fastuse:
  cancel_vl: 3
  modules:
    FastEat:
      # Do you want to enable the FastEat check?
      enabled: true
      vl_addition: 2
      # What delay should be enforced for eating an item?
      # Measured in ms
      min_time: 1350
    FastBow:
      # Do you want to enable the FastBow check?
      enabled: true
      vl_addition: 2
  # Action map
  action:
    6:
      - 'horizon notify %player% might be using item too fast'
    9:
      - 'horizon notify %player% is suspicious of using FastUse'
    12:
      - 'horizon notify %player% is kicked for using item too fast'
      - 'horizon kick %player% Using item too fast'
fly:
  cancel_vl: 10
  modules:
    Expect:
      # Do you want to enable the Expect check?
      enabled: true
      vl_addition: 2
  # Action map
  action:
    90:
      - 'horizon notify %player% might be trying to fly'
    120:
      - 'horizon notify %player% is suspicious of using Fly'
    160:
      - 'horizon notify %player% is kicked for flying'
      - 'horizon kick %player% Moving unexpectedly'

speed:
  cancel_vl: 10
  modules:
    # Do you want to enable the Expect check?
    Expect:
      enabled: true
      vl_addition: 2
    Dynamic:
      # Do you want to enable the Dynamic check?
      enabled: true
      vl_addition: 2
    Limit:
      # Do you want to enable the Limit check?
      enabled: true
      vl_addition: 2
    # Do you want to enable the Sprint check?
    Sprint:
      enabled: true
      vl_addition: 3
    # Do you want to enable the Strafe check?
    Strafe:
      enabled: true
      vl_addition: 4
    # Do you want to enable the Ladder check?
    Ladder:
      enabled: true
      vl_addition: 3
  # Action map
  action:
    80:
      - 'horizon notify %player% might be moving too fast'
    120:
      - 'horizon notify %player% is suspicious of using Speed'
    150:
      - 'horizon notify %player% is kicked for moving too fast'
      - 'horizon kick %player% Moving unexpectedly'

timer:
  cancel_vl: 10
  modules:
    # Do you want to enable the Tick check?
    Tick:
      enabled: true
      vl_addition: 1
  # Action map
  action:
    50:
      - 'horizon notify %player% might be sending too many movement packet'
    60:
      - 'horizon notify %player% is suspicious of using Timer'
    80:
      - 'horizon notify %player% is kicked for using Timer'
      - 'horizon kick %player% Too many packets'

cheststealer:
  cancel_vl: 3
  modules:
    # Do you want to enable the Limit check?
    Limit:
      enabled: true
      vl_addition: 2
  # Action map
  action:
    12:
      - 'horizon notify %player% might be using ChestStealer'
    15:
      - 'horizon notify %player% is suspicious of using ChestStealer'
    20:
      - 'horizon notify %player% is kicked for using ChestStealer'
      - 'horizon kick %player% ChestStealer'

killaura:
  cancel_vl: 8
  modules:
    Heuristic:
      # Do you want to enable the Heuristic check?
      enabled: true
      vl_addition: 3
    Click:
      # Do you want to enable the Click check?
      enabled: true
      vl_addition: 2
    # Do you want to enable the SuperKnockback check?
    SuperKnockback:
      enabled: true
      vl_addition: 6
  # Action map
  action:
    10:
      - 'horizon notify %player% might be using KillAura'
    12:
      - 'horizon notify %player% is suspicious of using KillAura'
    16:
      - 'horizon notify %player% is kicked for using KillAura'
      - 'horizon kick %player% KillAura'

nofall:
  cancel_vl: 1
  modules:
    GroundSpoof:
      # Do you want to enable the GroundSpoof check?
      enabled: true
      vl_addition: 1
  # Action map
  action:
    10:
      - 'horizon notify %player% might be using NoFall'
    12:
      - 'horizon notify %player% is suspicious of using NoFall'
    16:
      - 'horizon notify %player% is kicked for using NoFall'
      - 'horizon kick %player% NoFall'

phase:
  cancel_vl: 1
  modules:
    Collision:
      # Do you want to enable the Collision check?
      enabled: true
      vl_addition: 2
  # Action map
  action:
    20:
      - 'horizon notify %player% might be using Phase'
    25:
      - 'horizon notify %player% is suspicious of using Phase'
    30:
      - 'horizon notify %player% is kicked for using Phase'
      - 'horizon kick %player% Phase'

scaffold:
  cancel_vl: 6
  modules:
    EqualRotation:
      # Do you want to enable the Rotation check?
      enabled: true
      vl_addition: 3
    Rotation:
      # Do you want to enable the Rotation check?
      enabled: true
      vl_addition: 2
    Tower:
      # Do you want to enable the Tower check?
      enabled: true
      vl_addition: 3
  # Action map
  action:
    10:
      - 'horizon notify %player% might be using Scaffold'
    12:
      - 'horizon notify %player% is suspicious of using Scaffold'
    15:
      - 'horizon notify %player% is kicked for using Scaffold'
      - 'horizon kick %player% Scaffold'

esp:
  # Unused
  cancel_vl: 0
  modules:
    StorageESP:
      # Do you want to enable the StorageESP check?
      enabled: true
      # Unused
      vl_addition: 0
      # Check interval
      # Increasing it can save more performance
      # Decreasing it can make the check more accurate
      # Measured in tick
      check_interval: 3
    PlayerESP:
      # Do you want to enable the PlayerESP check?
      enabled: true
      # Unused
      vl_addition: 0
      # Check interval
      # Increasing it can save more performance
      # Decreasing it can make the check more accurate
      # Measured in tick
      check_interval: 3
  # Unused action map
  action: {}

healthtag:
  # Unused
  cancel_vl: 0
  modules:
    HealthSpoof:
      # Do you want to enable the HealthSpoof check?
      enabled: true
      # Unused
      vl_addition: 0
    ItemSpoof:
      # Do you want to enable the ItemSpoof check?
      enabled: true
      # Unused
      vl_addition: 0
      # Should Horizon spoof item amount?
      spoof_amount: true
      # Should Horizon spoof item enchantments?
      spoof_enchantments: true
      # Should Horizon spoof item durability?
      # This will also spoof unbreakable flag
      spoof_durability: true
  # Unused action map
  action: {}

bowaimbot:
  # Unused
  cancel_vl: 0
  modules:
    Velocity:
      # Do you want to enable the Velocity check?
      enabled: true
      # Unused
      vl_addition: 0
      # Multiply the velocity of arrows to make hack client failed to expect the arrow's trajectory.
      # It can be harmful if you set it too high.
      multiplier: 1.3
      # The y-axis will be added for arrows.
      # Your players may complain if you set it too high.
      y_addition: 0.1
  # Unused action map
  action: {}
